modLoader = "javafml"
loaderVersion = "[44,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "pridemod"
version = "${version}"
displayName = "Pride Mod"
authors = "Idk, add yourselves here"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.pridemod]]
modId = "forge"
mandatory = true
versionRange = "[44,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pridemod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,)"
ordering = "NONE"
side = "BOTH"